name = "fleetbox-preview"
account_id = "5a01620085c303479c1f5e6770a1a133"
route = "https://preview.fleetbox.io/*"
compatibility_date = "2022-04-03"
main = "./workers-site/index.js"

[build]
command = "npm run build"

[site]
bucket = "./build"
