name = "fleetbox-preview"
account_id = "5a01620085c303479c1f5e6770a1a133"
zone_id = "a7f53eeb9b959e98e4751f781bcd049f"
route = "https://preview.fleetbox.io/*"
site = {bucket = "./build", entry-point = "./workers-site"}
compatibility_date = "2022-04-03"

type = "javascript"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
