# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ci = is_ci
    setup_ci if ci
    app_store_connect_api_key(
      key_id: "W63DCTHP68",
      issuer_id: "c8eeae79-a596-4238-9eb5-1181d75ae57a",
      key_filepath: "./connect_api_key.p8"
    ) if ci
    changelog = read_changelog
    increment_build_number(
      xcodeproj: "Fleetbox.xcodeproj",
      build_number: latest_testflight_build_number + 1
    )
    match(type: "appstore", platform: "ios", readonly: ci)
    build_ios_app(scheme: "Fleetbox Release")
    # match(type: "mac_installer_distribution", platform: "catalyst", readonly: is_ci)
    # build_mac_app(scheme: "Fleetbox Release")
    upload_to_testflight(
      app_platform: "ios",
      changelog: changelog
    )
    # upload_to_testflight(app_platform: "mac")
  end

  lane :tests do
    ci = is_ci
    setup_ci if ci
    # A sort of soft-lint of the changelog
    read_changelog
    run_tests(
      scheme: "Fleetbox Debug",
      # Cover the whole spectrum, from small iPhone 8 to quite large to iPhone 13 Pro Max to much larger iPad
      devices: ["iPhone 13 Pro Max", "iPad (9th generation)", "iPhone 8"],
      testplan: "Everything"
    )
  end
end
