# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ci = is_ci
    setup_ci if ci
    app_store_connect_api_key(
      key_id: "32WWM3HYG9",
      issuer_id: "c8eeae79-a596-4238-9eb5-1181d75ae57a",
      key_filepath: "./connect_api_key.p8"
    ) if ci
    changelog = read_changelog
    version = get_version_number
    build_number = latest_testflight_build_number + 1
    increment_build_number(
      xcodeproj: "Fleetbox.xcodeproj",
      build_number: build_number
    )
    match(type: "appstore", platform: "ios", readonly: ci)
    build_ios_app(scheme: "Fleetbox Release")
    # if ENV['SENTRY_AUTH_TOKEN'] then
    #   sentry_upload_dif(
    #     org_slug: 'lutriseng',
    #     project_slug: 'fleetbox',
    #     include_sources: true
    #   )
    #   sentry_create_release(
    #     org_slug: 'lutriseng',
    #     project_slug: 'fleetbox',
    #     version: "#{version}+#{build_number}",
    #     app_identifier: "engineering.lutris.fleetbox.ios",
    #     finalize: true
    #   )
    # end
    # match(type: "mac_installer_distribution", platform: "catalyst", readonly: is_ci)
    # build_mac_app(scheme: "Fleetbox Release")
    upload_to_testflight(
      app_platform: "ios",
      changelog: changelog,
      distribute_external: true,
      groups: ["Fleetbox Internal Beta", "Fleetbox Private Beta"],
      reject_build_waiting_for_review: true
    )
    # upload_to_testflight(app_platform: "mac")
  end

  lane :tests do
    ci = is_ci
    setup_ci if ci
    # A sort of soft-lint of the changelog
    read_changelog
    run_tests(
      scheme: "Fleetbox Debug",
      devices: "iPhone 8",
      testplan: "Everything"
    )
  end
end
