name: App

on: [push]

jobs:
  test:
    name: Test App
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs fetch && git lfs checkout
      - name: Install tools
        run: brew bundle && bundle
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '13.2.1'
      - name: Run tests
        run: bundle exec fastlane tests
  testflight:
    name: Publish App to TestFlight
    concurrency: appstore-connect
    runs-on: macos-11
    # needs:
    #   - test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: todo
      - name: Add known hosts
        run: ssh-keyscan -H github.com > ~/.ssh/known_hosts
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs fetch && git lfs checkout
      - name: Install tools
        run: brew bundle && bundle
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '13.2.1'
      - name: Publish to TestFlight
        run: |
          echo '${{ secrets.CONNECT_API_KEY }}' > connect_api_key.p8
          bundle exec fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
