name: Lint

on: [push]

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs fetch && git lfs checkout
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
  schema:
    name: Check LineItemTypes.yml schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs fetch && git lfs checkout
      - name: Install tools
        run: wget https://github.com/mikefarah/yq/releases/download/v4.22.1/yq_linux_amd64 -O /usr/local/bin/yq && chmod +x /usr/local/bin/yq
      - name: Convert YAML to JSON
        run: |
          yq -o=json eval "Source/Model/Line Item Types/LineItemTypes.yml" | jq -c . > LineItemTypes.json
          cp "Source/Model/Line Item Types/LineItemTypes.schema.json" LineItemTypes.schema.json
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./LineItemTypes.schema.json
          INPUT_JSONS: ./LineItemTypes.json
