name: Preview

on: [push]

jobs:
  build:
    name: Build Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs fetch && git lfs checkout
      - name: Build
        run: cd Preview && npm ci && npm run build
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Checkout LFS objects
  #       run: git lfs checkout
  #     - run: cd Preview && npm ci && npm test
  deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs:
      - build
      # - test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs fetch && git lfs checkout
      - name: Publish
        run: cd Preview && npm ci && npm run publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
