name: Test

on: [push]

jobs:
  ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Run tests
        run: set -o pipefail && xcodebuild -scheme "Fleetbox (iOS)" -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13" clean test | xcpretty
  ipados:
    name: iPadOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Run tests
        run: set -o pipefail && xcodebuild -scheme "Fleetbox (iOS)" -destination "platform=iOS Simulator,OS=15.2,name=iPad (9th generation)" clean test | xcpretty
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Run tests
        run: set -o pipefail && xcodebuild -scheme "Fleetbox (iOS)" -destination "platform=OS X" clean test | xcpretty
