name: Test

on: [push]

jobs:
  test:
    name: Test ${{ matrix.destination }}
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - 'platform=iOS Simulator,OS=15.2,name=iPhone 13'
          - 'platform=iOS Simulator,OS=15.2,name=iPad (9th generation)'
          - 'platform=macOS'
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Install tools
        run: brew install yq jq && gem install xcpretty
      - name: Run tests
        run: set -o pipefail && xcodebuild -scheme Fleetbox -destination '${{ matrix.destination }}' -resultBundlePath TestResults clean test | xcpretty
      - name: Export tests results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()
