name: Test

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Install tools
        run: brew install --overwrite yq jq swiftlint && gem install xcpretty
      - run: swiftlint lint
      - name: Run build
        run: xcodebuild -scheme Fleetbox -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13" clean build | tee xcodebuild.log | xcpretty
      - run: swiftlint analyze --compiler-log-path xcodebuild.log
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Install tools
        run: brew install yq jq && gem install xcpretty
      - name: Run tests
        run: set -o pipefail && xcodebuild -scheme Fleetbox -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13" -resultBundlePath TestResults clean test | xcpretty
      - name: Export tests results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()
