name: Test

on: [push]

jobs:
  test:
    name: Test ${{ matrix.destination['name'] }}
    runs-on: macos-11
    strategy:
      matrix:
        destination:
          - name: iPhone 13
            destination: 'platform=iOS Simulator,OS=15.2,name=iPhone 13'
          - name: iPad (9th generation)
            destination: 'platform=iOS Simulator,OS=15.2,name=iPad (9th generation)'
# Waiting for GitHub actions to add macOS 12 support
#          - name: macOS
#            destination: 'platform=macOS'
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Install tools
        run: brew install yq jq fastlane && gem install xcpretty
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '13.3'
      - name: Build debug
        run: set -o pipefail && xcodebuild -scheme Fleetbox -destination '${{ matrix.destination['destination'] }}' -configuration Debug clean build | xcpretty
      - name: Build release
        run: set -o pipefail && xcodebuild -scheme Fleetbox -destination '${{ matrix.destination['destination'] }}' -configuration Release clean build | xcpretty
      - name: Run tests
        run: set -o pipefail && xcodebuild -scheme Fleetbox -destination '${{ matrix.destination['destination'] }}' -configuration Debug -resultBundlePath TestResults clean test | xcpretty
      - name: Export tests results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
          title: Test results for '${{ matrix.destination['name'] }}'
        if: success() || failure()
