name: Test

on: [push]

jobs:
  test:
    name: Test ${{ matrix.scheme }} on ${{ matrix.destination['name'] }}
    runs-on: macos-11
    strategy:
      matrix:
        destination:
          - name: iPhone 13
            destination: 'platform=iOS Simulator,name=iPhone 13'
          - name: iPad (9th generation)
            destination: 'platform=iOS Simulator,name=iPad (9th generation)'
# Waiting for GitHub actions to add macOS 12 support
#          - name: macOS
#            destination: 'platform=macOS'
        scheme:
          - Fleetbox Debug
          - Fleetbox Release
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Install tools
        run: brew install yq jq fastlane && gem install xcpretty
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '13.2.1'
      - name: Build
        run: set -o pipefail && xcodebuild -scheme '${{ matrix.scheme }}' -destination '${{ matrix.destination['destination'] }}' clean build | xcpretty
      - name: Test
        if: matrix.scheme == 'Fleetbox Debug'
        run: set -o pipefail && xcodebuild -scheme '${{ matrix.scheme }}' -destination '${{ matrix.destination['destination'] }}' -resultBundlePath TestResults clean test | xcpretty
      - name: Export test results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
          title: Test results for ${{ matrix.scheme }} on '${{ matrix.destination['name'] }}'
        if: (success() || failure()) && matrix.scheme == 'Fleetbox Debug'
